Gem::Specification.new do |s|
  s.name              = %q{refinerycms-inquiries}
  s.version           = %q{2.0.0}
  s.date              = %q{2012-02-06}
  s.summary           = %q{Inquiry handling functionality for the Refinery CMS project.}
  s.description       = %q{Inquiry handling functionality extracted from Refinery CMS to allow you to have a contact form and manage inquiries in the Refinery backend.}
  s.homepage          = %q{http://refinerycms.com}
  s.email             = %q{info@refinerycms.com}
  s.authors           = ["Resolve Digital"]
  s.require_paths     = %w(lib)

  s.add_dependency  'refinerycms-core', '~> 2.0.0'
  s.add_dependency  'filters_spam',     '~> 0.2'

  s.files             = [
    'app',
    'app/assets',
    'app/assets/stylesheets',
    'app/assets/stylesheets/refinery',
    'app/assets/stylesheets/refinery/inquiries',
    'app/assets/stylesheets/refinery/inquiries/inquiries.css.scss',
    'app/controllers',
    'app/controllers/refinery',
    'app/controllers/refinery/inquiries',
    'app/controllers/refinery/inquiries/admin',
    'app/controllers/refinery/inquiries/admin/inquiries_controller.rb',
    'app/controllers/refinery/inquiries/admin/settings_controller.rb',
    'app/controllers/refinery/inquiries/inquiries_controller.rb',
    'app/helpers',
    'app/helpers/refinery',
    'app/helpers/refinery/inquiries',
    'app/helpers/refinery/inquiries/inquiries_helper.rb',
    'app/mailers',
    'app/mailers/refinery',
    'app/mailers/refinery/inquiries',
    'app/mailers/refinery/inquiries/inquiry_mailer.rb',
    'app/models',
    'app/models/refinery',
    'app/models/refinery/inquiries',
    'app/models/refinery/inquiries/inquiry.rb',
    'app/models/refinery/inquiries/setting.rb',
    'app/views',
    'app/views/refinery',
    'app/views/refinery/inquiries',
    'app/views/refinery/inquiries/admin',
    'app/views/refinery/inquiries/admin/inquiries',
    'app/views/refinery/inquiries/admin/inquiries/_inquiry.html.erb',
    'app/views/refinery/inquiries/admin/inquiries/_submenu.html.erb',
    'app/views/refinery/inquiries/admin/inquiries/index.html.erb',
    'app/views/refinery/inquiries/admin/inquiries/show.html.erb',
    'app/views/refinery/inquiries/admin/settings',
    'app/views/refinery/inquiries/admin/settings/_confirmation_email_form.html.erb',
    'app/views/refinery/inquiries/admin/settings/_notification_recipients_form.html.erb',
    'app/views/refinery/inquiries/admin/settings/edit.html.erb',
    'app/views/refinery/inquiries/inquiries',
    'app/views/refinery/inquiries/inquiries/new.html.erb',
    'app/views/refinery/inquiries/inquiries/thank_you.html.erb',
    'app/views/refinery/inquiries/inquiry_mailer',
    'app/views/refinery/inquiries/inquiry_mailer/confirmation.text.erb',
    'app/views/refinery/inquiries/inquiry_mailer/notification.text.erb',
    'config',
    'config/locales',
    'config/locales/bg.yml',
    'config/locales/cs.yml',
    'config/locales/da.yml',
    'config/locales/de.yml',
    'config/locales/en-GB.yml',
    'config/locales/en.yml',
    'config/locales/es.yml',
    'config/locales/fr.yml',
    'config/locales/it.yml',
    'config/locales/lolcat.yml',
    'config/locales/lt.yml',
    'config/locales/lv.yml',
    'config/locales/nb.yml',
    'config/locales/nl.yml',
    'config/locales/pl.yml',
    'config/locales/pt-BR.yml',
    'config/locales/ru.yml',
    'config/locales/sk.yml',
    'config/locales/sl.yml',
    'config/locales/sv.yml',
    'config/locales/zh-CN.yml',
    'config/routes.rb',
    'db',
    'db/migrate',
    'db/migrate/20101208082840_create_inquiries.rb',
    'db/seeds.rb',
    'Gemfile',
    'Guardfile',
    'lib',
    'lib/gemspec.rb',
    'lib/generators',
    'lib/generators/refinery',
    'lib/generators/refinery/inquiries',
    'lib/generators/refinery/inquiries/inquiries_generator.rb',
    'lib/refinery',
    'lib/refinery/inquiries',
    'lib/refinery/inquiries/configuration.rb',
    'lib/refinery/inquiries/engine.rb',
    'lib/refinery/inquiries.rb',
    'lib/refinerycms-inquiries.rb',
    'license.md',
    'Rakefile',
    'readme.md',
    'refinerycms-inquiries.gemspec',
    'spec',
    'spec/models',
    'spec/models/refinery',
    'spec/models/refinery/inquiries',
    'spec/models/refinery/inquiries/inquiry_spec.rb',
    'spec/requests',
    'spec/requests/refinery',
    'spec/requests/refinery/inquiries',
    'spec/requests/refinery/inquiries/admin',
    'spec/requests/refinery/inquiries/admin/inquiries_spec.rb',
    'spec/requests/refinery/inquiries/inquiries_spec.rb',
    'spec/spec_helper.rb',
    'spec/support',
    'spec/support/refinery',
    'spec/support/refinery/factories.rb',
    'tasks',
    'tasks/rspec.rake'
  ]
  s.require_path = 'lib'
end
